# Generated by Django 2.2.7 on 2020-04-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_monitoring_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodeinterfaceipaddressserviceavailabilitycache',
            name='ip_address_availability_cache',
        ),
        migrations.AddField(
            model_name='nodeinterfaceipaddressavailabilitycache',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodeinterfaceipaddressavailabilitycache',
            name='status',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('unknown', 'unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='nodeinterfaceipaddressserviceavailabilitycache',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodeinterfaceipaddressserviceavailabilitycache',
            name='status',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('unknown', 'unknown')], default='unknown', max_length=10),
        ),
    ]
