# Generated by Django 2.2.7 on 2020-04-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_monitoring_api', '0002_auto_20200404_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkavailabilitycache',
            old_name='total_number_of_bound_ip_addresses',
            new_name='total_number_of_nodes',
        ),
        migrations.RenameField(
            model_name='nodeavailabilitycache',
            old_name='number_of_nodes_offline',
            new_name='number_of_bound_ip_address_offline',
        ),
        migrations.RenameField(
            model_name='nodeavailabilitycache',
            old_name='number_of_nodes_online',
            new_name='number_of_bound_ip_addresses_online',
        ),
    ]
