# Generated by Django 2.2.7 on 2020-04-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_monitoring_api', '0004_auto_20200405_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinterfaceipaddressavailabilitycache',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodeinterfaceipaddressserviceavailabilitycache',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
