# Generated by Django 2.2.7 on 2020-04-06 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_monitoring_api', '0005_auto_20200405_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodeavailabilitycache',
            name='number_of_bound_ip_address_offline',
        ),
        migrations.RemoveField(
            model_name='nodeavailabilitycache',
            name='number_of_bound_ip_addresses_online',
        ),
        migrations.RemoveField(
            model_name='nodeavailabilitycache',
            name='total_number_of_bound_ip_addresses',
        ),
        migrations.RemoveField(
            model_name='nodeinterfaceavailabilitycache',
            name='total_number_of_bound_ip_addresses',
        ),
        migrations.RemoveField(
            model_name='nodeinterfaceipaddressavailabilitycache',
            name='total_number_of_bound_ip_addresses',
        ),
    ]
