# Generated by Django 2.2.7 on 2020-04-06 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_monitoring_api', '0006_auto_20200406_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinterfaceavailabilitycache',
            name='node_availability_cache',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='infrastructure_monitoring_api.NodeAvailabilityCache'),
            preserve_default=False,
        ),
    ]
