# Generated by Django 2.2.7 on 2020-02-22 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perimeter_core', '0004_servicehandler'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perimeter_core.ServiceHandler'),
        ),
    ]
