# Generated by Django 2.2.7 on 2020-03-11 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perimeter_core', '0005_service_handler'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinterface',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodeinterface',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
