# Generated by Django 2.2.7 on 2020-03-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perimeter_core', '0006_auto_20200311_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinterfaceipaddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
